import Image from "next/image";
import Tafsir from "../components/Tafsir";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Tafsir ",
  description: "Generated by create next app",
};


export default function Home() {
  return (
   
    <div>
     <Tafsir/>  
    </div>
  );
}
