import Alquran from '@/components/Alquran'
import React from 'react'
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Tafsir - Islamic Teaching ",
  description: "Generated by create next app",
};


const page = () => {
  return (
    <div>
      <Alquran/>
    </div>
  )
}

export default page
