import React from 'react'
import Alquran1 from '@/components/Alquran1'
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Tafsir - Islamic Teaching ",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <Alquran1/>
    </div>
  )
}

export default page
